CleverTapSDK/CleverTap+ABTesting.h

- Deprecates Dynamic Variable and Screen AB methods.

SDK-526: Adds Deprecation Notice for ABTesting methods

---

CleverTapSDK/CTDeviceInfo.m

- Synchronising access for `deviceName` and `model` property
- Fixes crashes highlighted due to [CleverTap generateAppFields] method
- Addresses - #103

SDK-922: Refactor `CTDeviceInfo` Info Class

---

CleverTapSDK/CTUIUtils.h
CleverTapSDK/CTUIUtils.m
CleverTapSDK/CleverTap.m

- Refactored code to use enumerateKeysAndObjectsUsingBlock instead of allValues for [NSDictionary allValues].
- Removed memory warnings.

Mitigating [NSDictionary allValues] crashes and fixing memory warnings

---

CleverTapSDK/Inbox/controllers/CTInboxController.m

- Use `performBlock` instead of `performBlockAndWait` under `_deleteMessages`
- Create a local copy of user messages for the purpose of handling simultaneous insert and delete operations. In cases, when `self.user.messages` gets modified on multiple threads especially during the delete operation then it rarely result in error `*** _oset_objectAtIndex: index n beyond bounds [0 .. n-1]`

Refactor App Inbox Controller Class

---

CHANGELOG.md
CleverTap-iOS-SDK.podspec
CleverTapSDK.xcodeproj/project.pbxproj
CleverTapSDK/CTPreferences.m
CleverTapSDK/CleverTap.h
CleverTapSDK/CleverTap.m
CleverTapSDK/CleverTapBuildInfo.h
CleverTapSDK/CleverTapInstanceConfig.m
CleverTapSDK/CleverTapInstanceConfigPrivate.h
CleverTapSDKTests/CleverTapInstanceConfigTests.m
CleverTapSDKTests/CleverTapInstanceTests.m

People involved | @nzagorchev @akashvercetti
------------------|----------------------------------------
JIRA | [SDK-2177](https://wizrocket.atlassian.net/browse/SDK-2177), [SDK-2382](https://wizrocket.atlassian.net/browse/SDK-2382)
- Cache instance config
- Get global instance
- Allow NSString and NSSet unarchiving: this prevents errors such as:
- Attempted to decode a collection type 'Type' (subclass of 'Type') for key 'key'. 'Type' requires its subclasses to be explicitly added to the allowed classes list but it is not present.
- Example: `Attempted to decode a collection type 'NSString' (subclass of 'NSObject') for key 'accountId'. 'NSString' requires its subclasses to be explicitly added to the allowed classes list but it is not present. Allowing this has been a source of security …

SDK-2177 Get global instance

---

CHANGELOG.md
CleverTapSDK/CleverTap+Inbox.h
CleverTapSDK/CleverTap.m
CleverTapSDK/Inbox/controllers/CTInboxController.h
CleverTapSDK/Inbox/controllers/CTInboxController.m

- Added a public Api `deleteInboxMessagesforID` to delete multiple App Inbox messages by passing an array of App Inbox IDs.

Added a public api method to delete multiple app inbox messages in bulk

---

CleverTapSDK/Inbox/controllers/CTInboxController.m

Add hotfix for deleteInboxMessageForID crash when message ID is null or invalid

Fix crash in deleteInboxMessagesForIDs method

---

CleverTapSDK/CleverTap.m

fix Non-null judgment handling, it crashes all over the place when you pass nil

fix getLocationWithSuccess method parameter andError = nil is crash

---

CleverTapSDK/CleverTapJSInterface.m

- Updated to "properties" to make key consistent with profilePush and onUserLogin.
- Tested on Starter app in which we were already passing key as "properties" instead of "props".

[SDK-2943]: Updated recordEventWithProps argument key

---

CleverTapSDK/CTDeviceInfo.m
CleverTapSDK/CleverTap.m

- Updated logic to retrieve country code using NSLocale above iOS 16
- Updated logic to not send carrier name above iOS 16

SDK-3226 Carrier & Country Code changes above iOS 16

---

CleverTapSDK/CTEventBuilder.m
CleverTapSDKTests/CTEventBuilderTest.m

Recording an event with property name which is valid/clean, produces the following error:
`For event "eventName": Property value for property propertyName wasn't a primitive ((null)) `
Example: 
```
event: "Charged",
property: "Amount  "
value: 100
```
the SDK sends:
```
evtName: "Charged",
evtData: {}
```
Expected:
```
evtName: "Charged",
evtData: { "Amount": 100 }
```
Get the property value before changing the key in:
`build:withEventActions:completionHandler:`
Ensured charged event is working as expected as well:
`buildChargedEventWithDetails:andItems:completionHandler:`
Added unit tests to cover the above cases

SDK-3467 Fix event property name validation

---

CleverTapSDK/CTInAppDisplayViewController.m

If the `CTInAppDisplayViewController` shows an in-app before a scene becomes active, the `window` is `nil` and the view cannot be presented. This results in not being able to dismiss the controller which leads to not being able to display in-apps.
This reproduces sporadically and only when the device is offline.
Check if the window is initialized. If it is _not_:
- iOS 13 and above: set the flag `waitingForSceneWindow` to `YES`. Set the `animated` flag. Wait for the `UISceneDidActivateNotification` to be posted. Call again `showFromWindow:animated` to retry. A window will now be initialized from the scene that became active.
- older versions: This could happen only in the case of iOS 13 and scenes since for the older versions the window is initialized directly.
Added static debug and …

Fix display controller presented before scene became active

---

CleverTapSDK/InApps/CTInAppDisplayManager.m
CleverTapSDK/InApps/CleverTap+InAppsResponseHandler.m

1. In-apps are not discarded in CS mode.
2. In-apps are not discarded on App Launched SS mode.
1. Check the in-app rendering status in `prepareNotificationForDisplay`. If it is `CleverTapInAppDiscard` return and remove the in-app.
2. Move the check for the `CleverTapInAppDiscard` in-app rendering status before calling `evaluateOnAppLaunchedServerSide`

MC-1578 Fix in-apps not discarded

---

CleverTapSDK.xcodeproj/project.pbxproj
CleverTapSDK/CTConstants.h
CleverTapSDK/CTInAppDisplayViewController.m
CleverTapSDK/CTInAppNotification.h
CleverTapSDK/CTInAppNotification.m
CleverTapSDK/CTInAppUtils.h
CleverTapSDK/CTInAppUtils.m
CleverTapSDK/CTNotificationAction.h
CleverTapSDK/CTNotificationAction.m
CleverTapSDK/CTNotificationButton.h
CleverTapSDK/CTNotificationButton.m
CleverTapSDK/InApps/CTBaseHeaderFooterViewController.m
CleverTapSDK/InApps/CTCoverViewController.m
CleverTapSDK/InApps/CTHalfInterstitialViewController.m
CleverTapSDK/InApps/CTImageInAppViewController.m
CleverTapSDK/InApps/CTInAppDisplayManager.m
CleverTapSDK/InApps/CTInterstitialViewController.m
CleverTapSDK/InApps/CustomTemplates/CTCustomTemplateInAppData.h
CleverTapSDK/InApps/CustomTemplates/CTCustomTemplateInAppData.m
CleverTapSDKTests/CTEventBuilderTest.m
CleverTapSDKTests/InApps/CTInAppFCManagerTest.m
CleverTapSDKTests/InApps/CTNotificationActionTest.m
CleverTapSDKTests/InApps/CustomTemplates/CTCustomTemplateInAppDataTest.m

Refactor `CTInAppNotification`. Move the prepare notification logic for downloading the image and landscape image to the `CTInAppDisplayManager`.
Extend `CTInAppNotification` and `CTNotificationButton` to support custom functions.
- Add `CTCustomTemplateInAppData` to the `CTInAppNotification`
- Move the action from `CTNotificationButton` to the `CTNotificationAction`
- Add `CTCustomTemplateInAppData` to the `CTNotificationAction`
Commits: [efbc064](https://github.com/CleverTap/clevertap-ios-sdk/pull/330/commits/efbc0643008313674b39a29fd630aa14f08952b4), [60db706](https://github.com/CleverTap/clevertap-ios-sdk/pull/330/commits/60db706a65ea86196f0476a264b8ef7dc77a961f)

[MC-1466] Custom templates data in inapp notification (Custom Templates Part 3)

---

CleverTapSDK.xcodeproj/project.pbxproj
CleverTapSDK/CTConstants.h
CleverTapSDK/CTInAppDisplayViewController.h
CleverTapSDK/CTInAppDisplayViewController.m
CleverTapSDK/CTInAppNotificationDisplayDelegate.h
CleverTapSDK/CTInAppUtils.h
CleverTapSDK/CTInAppUtils.m
CleverTapSDK/CTNotificationButton.m
CleverTapSDK/CleverTap.m
CleverTapSDK/InApps/CTAlertViewController.m
CleverTapSDK/InApps/CTBaseHeaderFooterViewController.m
CleverTapSDK/InApps/CTInAppDisplayManager.h
CleverTapSDK/InApps/CTInAppDisplayManager.m
CleverTapSDK/InApps/CTInAppEvaluationManager.m
CleverTapSDK/InApps/CTInAppHTMLViewController.m
CleverTapSDK/InApps/CustomTemplates/CTCustomTemplate-Internal.h
CleverTapSDK/InApps/CustomTemplates/CTCustomTemplatesManager-Internal.h
CleverTapSDK/InApps/CustomTemplates/CTCustomTemplatesManager.h
CleverTapSDK/InApps/CustomTemplates/CTCustomTemplatesManager.m
CleverTapSDK/InApps/CustomTemplates/CTTemplateContext-Internal.h
CleverTapSDK/InApps/CustomTemplates/CTTemplateContext.h
CleverTapSDK/InApps/CustomTemplates/CTTemplateContext.m
CleverTapSDK/InApps/CustomTemplates/CTTemplatePresenter.h
CleverTapSDKTests/InApps/CTInAppEvaluationManagerTest.m
CleverTapSDKTests/InApps/CustomTemplates/CTCustomTemplatesManagerTest.m
CleverTapSDKTests/InApps/CustomTemplates/CTTemplateContextTest.m
CleverTapSDKTests/InApps/CustomTemplates/CTTemplatePresenterMock.h
CleverTapSDKTests/InApps/CustomTemplates/CTTemplatePresenterMock.m

Present custom in-app templates. 
Call the presenter onPresent with the TemplateContext. 
Dismiss the notification from the in-app queue when context dismissed is called.
- `CTTemplateContext` merging and getting of argument values.
- Move `CTInAppNotificationDisplayDelegate` to a separate file.
- Modify the `CTInAppDisplayManager` to use a static `CTInAppNotification currentlyDisplayingNotification` instead of the display controller to check if a notification is currently being displayed. 
- `checkPendingNotifications` uses `NSNotificationCenter` to post a notification when a pending notification `CTInAppNotification` needs to be displayed. This way the in-app notification can be displayed by the correct `CTInAppDisplayManager` instance in case of multi instances.

[MC-1468] Custom templates present and dismiss (Custom Templates Part 4)

---

CleverTapSDK/CTConstants.h
CleverTapSDK/CTInAppDisplayViewController.h
CleverTapSDK/CTInAppDisplayViewController.m
CleverTapSDK/CleverTapJSInterface.h
CleverTapSDK/CleverTapJSInterface.m
CleverTapSDK/CleverTapJSInterfacePrivate.h
CleverTapSDK/InApps/CTInAppDisplayManager.m
CleverTapSDK/InApps/CTInAppHTMLViewController.h
CleverTapSDK/InApps/CTInAppHTMLViewController.m
CleverTapSDK/InApps/CustomTemplates/CTTemplateContext.m
CleverTapSDKTests/InApps/CustomTemplates/CTTemplateContextTest.m

Support triggering actions from HTML in-app notifications.
Modify the `CleverTapJSInterface` to support `triggerInAppAction` message. The interface needs to be initialized with config and `CTInAppDisplayViewController` controller.
The interface is now initialized from inside the controller (in this case `CTInAppHTMLViewController` which extends `CTInAppDisplayViewController`) and holds a weak reference to that controller. The action can be triggered using the controller, call the delegate, and hide the notification. This is similar to how the button clicks are handled in `buttonTapped:` and `handleButtonClickFromIndex:`.
Commits 
cb41a661b37579056e0878d8803133355cb71102 
970c9bb5b19710e39bd39b58424c76433ffb6eb9

[MC-1472] In-app actions js interface (Custom Templates Part 7)

---

CleverTapSDK/FileDownload/CTFileDownloadManager.m
CleverTapSDK/FileDownload/CTFileDownloader.m

- `removeAllFilesWithCompletionBlockReturn:` return after the completion if there is an error
- `synchronize` the `dispatch_group_leave(group)` call from the downloads in progress callback. The callback is executed from the concurrent queue async. Ensurez that `dispatch_group_leave(group)` is called exactly once for each `dispatch_group_enter(group)`.

File download changes

---

CleverTapSDK.xcodeproj/project.pbxproj
CleverTapSDKTests/CTLocalDataStoreTests.m
CleverTapSDKTests/CTUserInfoMigratorTest.m
CleverTapSDKTests/InApps/CTInAppEvaluationManagerTest.m

Added Unit Test cases for
- CTUserInfoMigrator
- EvaluateOnUserAttributeChange
- getUserAttributeChangeProperties

SDK-3831 - Adding unit test cases

---

CleverTapSDK.xcodeproj/project.pbxproj
CleverTapSDK/CTConstants.h
CleverTapSDK/CTInAppNotification.m
CleverTapSDK/CleverTap.m
CleverTapSDK/CleverTapInternal.h
CleverTapSDK/InApps/CTInAppDisplayManager.m
CleverTapSDK/InApps/CTInAppStore.h
CleverTapSDK/InApps/CTInAppStore.m
CleverTapSDK/InApps/CTLocalInApp.m
CleverTapSDK/InApps/CleverTap+InAppsResponseHandler.m
CleverTapSDK/InApps/CustomTemplates/CTCustomTemplatesManager-Internal.h
CleverTapSDK/InApps/CustomTemplates/CTCustomTemplatesManager.m
CleverTapSDK/InApps/CustomTemplates/CTTemplateContext-Internal.h
CleverTapSDK/InApps/CustomTemplates/CTTemplateContext.m
CleverTapSDKTests/InApps/CTInAppStoreTest.m
CleverTapSDKTests/InApps/CustomTemplates/CTCustomTemplatesManagerTest.m
CleverTapSDKTests/InApps/CustomTemplates/CTFileDownloaderCustomTemplatesMock.h
CleverTapSDKTests/InApps/CustomTemplates/CTFileDownloaderCustomTemplatesMock.m
CleverTapSDKTests/InApps/CustomTemplates/CTTemplateContextTest.m
CleverTapSDKTests/InApps/InAppHelper.m

Download files for Custom Templates and App Functions. Preload the files in Client side mode. Download the files before showing the notification and presenting a custom app function action.
- Preload the files in CS mode when the in-app notifications are fetched (see `InAppsResponseHandler fileArgsURLsForInAppData:`). 
- Preload the files for actions of custom templates (see `CTCustomTemplatesManager fileArgsURLsForInAppData:`).
- Download the files when preparing the notification for display (see `CTInAppDisplayManager`). 
- Download the files when triggering a custom action with visual=false and presenting it (see `CTInAppDisplayManager triggerCustomTemplateAction:forNotification:`).

[MC-1755] Implement custom templates file arguments (Custom Templates Part 8) 

---

CleverTapSDK.xcodeproj/project.pbxproj
CleverTapSDK/CTConstants.h
CleverTapSDK/CTConstants.m
CleverTapSDK/CleverTap+CTVar.h
CleverTapSDK/CleverTap.h
CleverTapSDK/CleverTap.m
CleverTapSDK/ProductExperiences/CTVar-Internal.h
CleverTapSDK/ProductExperiences/CTVar.h
CleverTapSDK/ProductExperiences/CTVar.m
CleverTapSDK/ProductExperiences/CTVarCache.h
CleverTapSDK/ProductExperiences/CTVarCache.m
CleverTapSDK/ProductExperiences/CTVariables.h
CleverTapSDK/ProductExperiences/CTVariables.m
CleverTapSDKTests/FileDownload/CTFileDownloadTestHelper.h
CleverTapSDKTests/FileDownload/CTFileDownloadTestHelper.m
CleverTapSDKTests/FileDownload/CTFileDownloaderMock.h
CleverTapSDKTests/FileDownload/CTFileDownloaderMock.m
CleverTapSDKTests/ProductExperiences/CTVarCache+Tests.h
CleverTapSDKTests/ProductExperiences/CTVarCacheTest.m
CleverTapSDKTests/ProductExperiences/CTVarTest.m
CleverTapSDKTests/ProductExperiences/CTVariables+Tests.m
CleverTapSDKTests/ProductExperiences/CTVariablesTest.m

- Added support for File in PE Variables
- Adds new CleverTap APIs `onVariablesChangedAndNoDownloadsPending` and `onceVariablesChangedAndNoDownloadsPending`.
- Adds new `fileIsReady` callback in CTVarDelegate when file is downloaded.
- Added unit tests for File type variables

[MC-1739] PE File Variables

---

CleverTapSDK/FileDownload/CTFileDownloader.m
CleverTapSDKTests/FileDownload/CTFileDownloadManagerTests.m
CleverTapSDKTests/FileDownload/CTFileDownloader+Tests.h
CleverTapSDKTests/FileDownload/CTFileDownloaderTests.m

Remove the files downloaded by SDWebImage and clear the previous preferences when migrating to the new File Downloader. 
SDWebImage does not provide direct API to move the files to a different location, hence it is safer to remove them and the File Downloader will download the actively used files.
Use SDWebImage to remove the files from the previous storage.
Add unit test which downloads files mimicking the legacy logic and then asserts the files are deleted after migration.

[FileDownloader] Remove SDWebImage download files when migrating

---

CleverTapSDK/FileDownload/CTFileDownloader.h
CleverTapSDK/FileDownload/CTFileDownloader.m
CleverTapSDK/ProductExperiences/CTVarCache.m
CleverTapSDKTests/FileDownload/CTFileDownloaderTests.m

- The file expiry timestamp were not getting updated for PE File vars if file was already present because we were only updating the expiry timestamp when `downloadFiles:` is called. For InApps downloadFiles: are called for all urls, but for PE File Var we are calling it for urls which are not present.
- The expired files were not getting deleted if we don't call `downloadFiles:` anywhere. So added logic to check for expired files and delete them when `CTFileDownloader` is initialised only, ie on every App launch.

[PE File Vars] Updated file expiry logic

---

CleverTapSDK/InApps/CustomTemplates/CTCustomTemplate.m
CleverTapSDK/InApps/CustomTemplates/CTTemplateContext.m

Overwrite debug description to return detailed information on `CTTemplateContext` and `CTCustomTemplate`.
`CTTemplateContext` - returns the template name and argument values description. Uses the template name or empty string for actions.
`CTCustomTemplate` - returns the template name and arguments description. The arguments are `CTTemplateArgument` which already overrides the description.

Add template and template context debug descriptions (Custom Templates Part 9)

---

CleverTapSDK/CTInAppDisplayViewController.h
CleverTapSDK/CTInAppDisplayViewController.m
CleverTapSDK/InApps/CTInAppHTMLViewController.m

Fix html view controller presented before scene became active. See details in the initial PR which fixes this in the `CTInAppDisplayViewController`: #309 
Move the initialization and setting of the window to a separate method. Reuse the method in the `CTInAppHTMLViewController`.
These changes and PR are to the `custom_inapp_templates` branch since there are other changes to the `CTInAppHTMLViewController` and this will make the merging easier later on.

[MC-1823] Fix html view controller presented before scene became active

---

CleverTapSDK/CleverTapJSInterface.m
CleverTapSDK/CleverTapJSInterfacePrivate.h
CleverTapSDK/InApps/CTInAppHTMLViewController.m

Include the CleverTap SDK version in the JS interface. The version should be accessible by the HTML in-app notifications. This enables the JavaScript in the Web View to get the version and execute code based on the SDK version capabilities and features.
Add `cleverTapIOSSDKVersion` variable to the `window`. The variable is set to the `WR_SDK_REVISION` which is the integer version of the SDK. The script is added at document start, only to the main frame.

[MC-1788] Add SDK version as window variable to the JS interface

---

CleverTapSDK/CleverTap.h
CleverTapSDK/CleverTap.m

Add `activeContextForTemplate:` to `CleverTap.h` so customers can use it for convenience.
Use the `CTCustomTemplatesManager` custom template manager `activeContextForTemplate:`.

Expose activeContextForTemplate

---

CleverTapSDK/InApps/CustomTemplates/CTCustomTemplatesManager.m

The number of templates defined is expected to be a relatively small number. The sync is performed only during integration to register the templates in the Dashboard. There is no need to enumerate concurrently.
Enumerate synchronously.

Sync templates enumerate synchronously

---

CleverTapSDK/CleverTap.m
CleverTapSDK/InApps/CustomTemplates/CTCustomTemplateBuilder.m
CleverTapSDKTests/InApps/CustomTemplates/CTCustomTemplatesManagerTest.m
CleverTapSDKTests/InApps/CustomTemplates/CTTemplateContextTest.m

| JIRA | [MC-2003](https://wizrocket.atlassian.net/browse/MC-2003) |
|-|-|
Defining a boolean inside a dictionary in swift, results in an error when syncing it.
The definition is:
```swift
templateBuilder.addArgument("map", dictionary: [
"int": 0,
"bool": true
])
```
Error:
```
Define Custom Templates error: Variable `map.bool` has value that does not conform to its type.
```
The default value is sent as `true` but the type is set as `number`.
The same definition works in objective-c. 
The `bool` can be defined inside the map using dot notation `map.bool` successfully.
Check the inner type of the `NSNumber` to find if it is a boolean `__NSCFBoolean` or a number `__NSCFNumber`.
Unit tests and Manual QA
[MC-2003]: https://wizrocket.atlassian.net/browse/MC-2003?atlOrigin=eyJpIjoiNWRkNTljNzYxN …

[MC-2003] Custom template dictionary swift bool

---

CleverTapSDK/CleverTap.m

| JIRA | [MC-1886](https://wizrocket.atlassian.net/browse/MC-1886) |
|-|-|
CleverTap push notification open action is handled twice when using Leanplum SDK. The notification is handled by the `application:didFinishLaunchingWithOptions:` in CleverTap and also handled from `UNUserNotificationCenterDelegate` `didReceive` method.
If the notification is _not_ handled by Leanplum, there are cases where it is _not_ handled at all. This happens when the application already became active and CleverTap does _not_ handle the deeplink since app is in foreground. The method `_appEnteredForegroundWithLaunchingOptions` calls `_handlePushNotification` with the launch options which passes `openDeepLinksInForeground:NO`.
Check if the library is `Leanplum`. Do _not_ handle the notification in this case, and …

[MC-1886] Do not handle push on launch if Leanplum library

---

CleverTapSDK/CTValidationResultStack.m

| What           | Where/Who                         |
|----------------|-----------------------------------|
| JIRA Issue     | [SDK-4102](https://wizrocket.atlassian.net/browse/SDK-4102)                           |
| People Involved| [@akashvercetti](https://github.com/akashvercetti) [@kushCT](https://github.com/kushCT)  |
Some clients are facing crashes in their application from the CTValidator class. The issue might be due to accessing invalid memory while the validations results are been added to the stack or been removed. To avoid this, we have added them in synchronized blocks
- Updated CTValidator class with synchronized blocks while pushing and popping Validation results.
Manual.
No.
[SDK-4102]: https://wizrocket.atlassian.net/browse/SDK-4102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3 …

Added push and pop validation in synchronized block

---

CleverTapSDK.xcodeproj/project.pbxproj
CleverTapSDK/CTConstants.h
CleverTapSDK/CTInAppDisplayViewController.m
CleverTapSDK/CTInAppUtils.h
CleverTapSDK/CTInAppUtils.m
CleverTapSDK/CleverTapJSInterface.m
CleverTapSDK/InApps/CTInAppHTMLViewController.m
CleverTapSDKTests/InApps/CTInAppDisplayViewControllerMock.h
CleverTapSDKTests/InApps/CTInAppDisplayViewControllerMock.m
CleverTapSDKTests/InApps/CTInAppDisplayViewControllerTests.m

- Added parsing of urls on open-url action.
- This will track the parameters in url for in-app in Notification Clicked event.
- This will also parse `__dl__` if `wzrk_c2a` is present in query parameters or action URL.
- Fixes an issue where wzrk_c2a value is passed as null to backend when we receive null for callToAction value in webView message handler. Example: 
```
var message = { action:'triggerInAppAction', actionJson: actionJson, callToAction: null, buttonId: null };
window.webkit.messageHandlers.clevertap.postMessage(message);
```
For above script we get message as below where value for callToAction is of NSNull class:
```
{
...
buttonId = "<null>";
callToAction = "<null>";
}
```

[MC-2363] Add parsing of url params on open-url action

---

CleverTapSDK/CTLocalDataStore.h
CleverTapSDK/CTLocalDataStore.m

We need to add in-memory storage for first time events and profile
Added in-memory collection (NSSet) for quickly accessing already tracked events. Add the event to this NSSet when the event is checked for First-time and the event exists in the database

 [MC - 2090] In-memory storage events

---

CleverTapSDK/CTConstants.h
CleverTapSDK/EventDatabase/CTEventDatabase.h
CleverTapSDK/EventDatabase/CTEventDatabase.m
CleverTapSDKTests/EventDatabase/CTEventDatabaseTests.m

We need to add limits to event stored in storage. Based on discussion, the max row limit for table will be `(2048 unique events + 256 unique profile properties) * 5 users = 11520 rows`. The number of rows to cleanup is (2048+256). So number of rows to be deleted will be equal to (totalRowCount - (maxLimit - numberOfRowsToCleanup)). Rows will be deleted based on last timestamp where least recently used will be deleted first and the cleanup is done when instance is created or every app launch.
- Added method `deleteLeastRecentlyUsedRows:numberOfRowsToCleanup:` which is called when instance is created. Added index on `lastTs` column which enhance performance while deletion when table is large. We have also added functionality to rollback if deletion gives any error and commit when success.
- …

[MC-2106] Add event storage limits

---

CleverTapSDK/CTLocalDataStore.m
CleverTapSDK/CleverTapEventDetail.h
CleverTapSDK/CleverTapEventDetail.m
CleverTapSDK/EventDatabase/CTEventDatabase.h
CleverTapSDK/EventDatabase/CTEventDatabase.m
CleverTapSDKTests/EventDatabase/CTEventDatabaseTests.m

- Normalize the event name in database.
- Added `normalizedEventName` column to the `CTUserEventLogs` table.
- While inserting into table add the original event name along with normalized name.
- Query the table based on normalized name only.
- Added `normalizedEventName` and `deviceID` to `CleverTapEventDetail` class to include while event details are fetched.
- Added `upsertEvent` method to insert if event not exists and update when exists.
- Fixed the unit test cases.

[MC-2430] Normalize event names

---

CleverTapSDK/CTLocalDataStore.h
CleverTapSDK/CTLocalDataStore.m
CleverTapSDK/CleverTap.h
CleverTapSDK/CleverTap.m

- Added following new public apis for accessing new event database methods.
`getUserEventLogCount:`
`getUserEventLog:`
`getUserEventLogFirstTs:`
`getUserEventLogLastTs:`
`getUserEventLogHistory`
`getUserAppLaunchCount`
`getUserLastVisitTs`
- Deprecated following old apis which read previous storage.
`eventGetOccurrences:`
`eventGetDetail:`
`eventGetFirstTime:`
`eventGetLastTime:`
`userGetEventHistory`
`userGetTotalVisits`
`userGetPreviousVisitTime`

[MC-2429] Add new public apis - Multi triggers

---

CleverTapSDK/CTInAppNotification.m
CleverTapSDK/InApps/CTInAppDisplayManager.m

Fixes custom in-app device orientation check. 
The default value for the `CTInAppNotification` `hasPortrait` is `YES` and the default value for `hasLandscape` is `NO` which causes custom in-apps to not be presented if the device is in Landscape.
The customer's implementation handles the presentation of custom in-apps so it should handle if the device orientation is supported for the in-app.
The `deviceOrientationIsLandscape` check requires the main thread. The implementation in `CTInAppNotificaton` was making this check async. 
The orientation check is now performed in the `CTInAppDisplayManager prepareNotificationForDisplay:` method. The check is done in `runSyncMainQueue` block which ensures code executes on main thread.
The orientation check returns if the in-app type is Custom.

[SDK-4476] Fix custom in-app device orientation check

---

CleverTapSDKTests/BaseTestCase.h
CleverTapSDKTests/BaseTestCase.m

Fix an exception in `BaseTestCase`: `data is nil`. The exception is caused by the code in `BaseTestCase onStubActivation`. Make the call use weak self reference and add nil checks in it.
Remove `BaseTestCase` unused methods.

BaseTestCase fixes

---

CleverTapSDK/CleverTapJSInterface.m
CleverTapSDK/InApps/CTInAppDisplayManager.m

Fix for notification clicked getting registered while dismissing HTML in-App. For Javascript support in In-App Notifications by calling the JS method if we add the action as 'dismissInAppNotification' in the dashboard, the inapp will get closed without registering notification clicked  event:
```
if (window.webkit && window.webkit.messageHandlers && window.webkit.messageHandlers.clevertap) { 
var message = { action:'dismissInAppNotification'};
window.webkit.messageHandlers.clevertap.postMessage(message);
}
}
```

SDK-4496 - Fix notification clicked getting registered while dismissing HTML in-App

---

CleverTapSDK/CTInAppNotification.h
CleverTapSDK/CTInAppNotification.m
CleverTapSDK/InApps/CTInAppDisplayManager.m

Typecasting [[NSDate date] timeIntervalSince1970] to an int resulted in the same value as notification.timeToLive, causing the elapsed condition to be bypassed.
https://wizrocket.atlassian.net/browse/SDK-4474
Resolution: Implemented a fix to enable TTL validation by using NSTimeInterval instead of int.

SDK-4474 TTL fix for InApps

---

CleverTapSDK/CTLocalDataStore.h
CleverTapSDK/CTLocalDataStore.m
CleverTapSDK/CTProfileBuilder.h
CleverTapSDK/CTProfileBuilder.m
CleverTapSDK/CleverTap.m
CleverTapSDKTests/CTLocalDataStoreTests.m

1. The updated value is not used in the completion callbacks for the user attributes methods. Remove it and remove the code that calculates it.
2. Persist the profile changes in `processEvent:withType:` even if in-apps are not supported.
3. Rename `getUserAttributeChangeProperties:` to `userAttributeChangeProperties:`.
4. In `userAttributeChangeProperties:` method, do not construct the multi value, since the multi value user attributes are not supported by the user attributes triggering. 
The multi value attributes are already persisted and calling the method `_constructLocalMultiValueWithOriginalValues:forKey:usingCommand:localDataStore:` produces an empty array.
The multi values are persisted in the method `_handleMultiValueProfilePush:updatedMultiValue:errors:`.

[User Attributes] Remove unnecessary calls and parameters

---

CleverTapSDK/CTProfileBuilder.m

If there is no cached value, ie this is the first time increment/decrement is called for a user property, the value will not be persisted since the cached value is nil.
Set the `newValue` to equal the current `value`. If there is a cached value, the new value will be calculated, otherwise it will be the current value.

Fix increment/decrement value persistence when no cached value

---

CleverTapSDK/CTInAppDisplayViewController.m

Found this bug during dev testing - InApp was getting cropped if height exceeded due to aspect ratio

SDK-4433 AIB - InApps height fix in landscape mode

---

.github/workflows/update_package_swift.yml

The cloudfront server does not point to the updated artifact after a new XCFramework is uploaded to s3. An additional command has been added to the workflow to make it invalidate its cache for this purpose.

Invalidate cloudfront cache after uploading a new xcframework

---

CleverTapSDK/InApps/CustomTemplates/CTCustomTemplatesManager.m

Currently we are sending system defined templates in sync payload which leads to `No new templates are synced` error and not syncing new templates. We have filtered out the system defined templates as they are not needed during sync templates.

[SDK-4916] Filter out system templates in sync payload
