- CleverTapSDK/CTInAppNotification.h
- CleverTapSDK/CTInAppNotification.m
- CleverTapSDK/CleverTap.m
- Added TTL to handle stale InApps
> task(InApp): added TTL to handle stale InApps

- CleverTapSDK/Inbox/cells/CTCarouselMessageCell.m
- Fixes Inbox type carousel page control misalignment in landscape mode
> Fixes App inbox landscape misalgniment

- README.md
- Restructured README
- Updated Integration & Installation docs
- Added link to Rich Push Notifications Libraries & Geofence SDK
> Improves GitHub README

- CleverTapSDK/CleverTap.m
Accessing instances of UIApplication on any queue other than Main Queue causes Xcode's Thread Sanitizers to raise warnings & can result in undefined behaviour as all UIKit objects must always be accessed from the Main Queue.
> SDK-426: moved UIApplication accesses to Main Queue

- CleverTapSDK/CleverTap.m
- Remove unknown JSON attributes for Test In-Apps, Native Display and App Inbox
> Remove unknown JSON attributes from Test Push Payload

- README.md
- Update documentation for integrating SDWebImage under the Manual Installation section
> SDK-661: Update Manual Installation Guide

- CleverTapSDK/CTInAppNotification.h
- CleverTapSDK/CTInAppNotification.m
- CleverTapSDK/CleverTap+Inbox.h
- CleverTapSDK/CleverTap.m
- CleverTapSDK/Inbox/controllers/CTInboxController.h
- CleverTapSDK/Inbox/controllers/CTInboxController.m
- Fixes Negative to Unsigned for InApps and AppInbox
> SDK-707: Fixes Type Mismatch (Negative to Unsigned)

- CleverTapSDK/CleverTap+Inbox.h
- CleverTapSDK/Inbox/config/CleverTapInboxStyleConfig.m
- CleverTapSDK/Inbox/controllers/CleverTapInboxViewController.m
Added a "firstTabTitle" field to App Inbox Style Config to customise the title of the first tab at App Inbox.
> Customise the title of the first tab at App Inbox 

- CleverTapSDK/CleverTapJSInterface.m
- SwiftStarter/SwiftStarter/Supporting Files/sampleHTMLCode.html
- Added functionality to record charged event at the JS interface using an action called "recordChargedEvent".
> added a javascript action called "recordChargedEvent" for Custom HTML in-app notifications and JS Interface

- CleverTapSDK/Inbox/controllers/CTInboxController.m
Synchronously performs App Inbox delete message operation to mitigate race condition crashes
> SDK-739: App Inbox Improvements

- CleverTapSDK/CleverTap.m
Added a safety check around ifvString key.
> Mitigated a possible null ifvString key at generateAppFields() in CleverTap.m

- CHANGELOG.md
- CleverTap-iOS-SDK.podspec
- CleverTapSDK/CleverTapBuildInfo.h
- Update BuildInfo
- Update to CleverTap iOS SDK podspec
> Prepare CleverTap iOS SDK 4.0.0

- CleverTapSDK/CleverTap.m
Applied locks to make certain shared instance methods thread safe
> Making shared instance creation methods thread safe

- CleverTapSDK/CTLocalDataStore.h
- CleverTapSDK/CTLocalDataStore.m
- CleverTapSDK/CTLoginInfoProvider.h
- CleverTapSDK/CTLoginInfoProvider.m
- CleverTapSDK/CleverTap.m
Modified `removeValueForKey` method to remove locally cached values
> Removing User Property(s) Preserving Identity Management

- CHANGELOG.md
- CleverTap-iOS-SDK.podspec
Updated changelog and podspec versions
> Prepare v.4.1.0

- CleverTapSDK/Inbox/controllers/CTInboxController.m
As Crash logs were pointed to this key - user.messages, added a suggestive fix to mitigate core data crash around user.messages usage
> SDK-1624 App Inbox crash

- CHANGELOG.md
- CleverTap-iOS-SDK.podspec
- CleverTapSDK/CleverTapBuildInfo.h
- Updated ChangeLog and podspec.
> Prepare 4.1.1

- CHANGELOG.md
- CleverTap-iOS-SDK.podspec
- CleverTapSDK/CTLocalDataStore.m
- CleverTapSDK/CleverTapBuildInfo.h
- CleverTapSDK/FeatureFlags/controllers/CTFeatureFlagsController.m
- CleverTapSDK/Inbox/controllers/CTInboxController.m
- iOS 16 support - warning fixes
- App inbox research and possible fix
> Release iOS SDK v4.1.2: SDK-2193 and SDK-1967

- CHANGELOG.md
- CleverTap-iOS-SDK.podspec
- CleverTapSDK/CTValidator.m
- CleverTapSDK/CleverTap.h
- CleverTapSDK/CleverTap.m
- CleverTapSDK/CleverTapBuildInfo.h
- Allowed additional special characters when setting a custom CleverTap ID.
> Changes for custom CleverTap ID 

- CHANGELOG.md
- CleverTap-iOS-SDK.podspec
- CleverTapSDK/CleverTapBuildInfo.h
- CleverTapSDK/InApps/CTInAppHTMLViewController.m
- Hotfix for embedded videos not rendering in html inapp messages
> Hotfix for embedded videos not rendering in html inapp messages

- CleverTapSDK/CTLocationManager.h
- CleverTapSDK/CTLocationManager.m
- CleverTapSDK/CleverTap+Inbox.h
- CleverTapSDK/CleverTap.h
- CleverTapSDK/CleverTap.m
- CleverTapSDK/Inbox/controllers/CTInboxController.h
- CleverTapSDK/Inbox/controllers/CTInboxController.m
- SwiftStarter/SwiftStarter/ViewController.swift
- Added public API method 'markReadInboxMessagesForIDs'  for marking app inbox messages as read in bulk
> SDK-2483_markReadInboxMessagesPublicAPI

- CleverTapSDK/Inbox/controllers/CTInboxController.m
- Fixed a bug where CoreData would crash with threading inconsistency exceptions.
> Fixes for app inbox coredata crashes

- CleverTapSDK/CTLocationManager.h
- CleverTapSDK/CTLocationManager.m
- CleverTapSDK/CleverTap.h
- CleverTapSDK/CleverTap.m
- Added public method 'enableLocation' to enable location in case of SPM
> SDK-2630_locationAPISupportForSPM

- CleverTapSDK/CleverTap+Inbox.h
- CleverTapSDK/CleverTap.m
- Added public API method 'dismissAppInbox' to dismiss CleverTapInboxViewController.
> SDK-2812_dismissInboxPublicAPI

- CHANGELOG.md
- CleverTap-iOS-SDK.podspec
- CleverTapSDK/CleverTapBuildInfo.h
- Updated changelog, podspec and buildinfo files.
> Prepare_v4.2.1

- CHANGELOG.md
- CleverTap-iOS-SDK.podspec
- CleverTapSDK/CTDeviceInfo.h
- CleverTapSDK/CTLocalDataStore.m
- CleverTapSDK/CTPlistInfo.h
- CleverTapSDK/CTPlistInfo.m
- CleverTapSDK/CTPreferences.h
- CleverTapSDK/CTPreferences.m
- CleverTapSDK/CleverTap.h
- CleverTapSDK/CleverTap.m
- CleverTapSDK/CleverTapBuildInfo.h
- CleverTapSDK/Inbox/models/CTUserMO+CoreDataProperties.h
- CleverTapSDK/Inbox/models/CTUserMO+CoreDataProperties.m
- Compilation Error Fixes for Xcode 14.3+
> Compilation Error Fixes for Xcode 14.3+

- CleverTapSDK/CTPreferences.m
- CleverTapSDK/CleverTap.m
- Refactored `appEnteredBackground` method to perform background tasks with expiration handler.
> Minor improvements for tasks in background state

- CleverTapSDK/CleverTap.m
- Updated hello request URL to `https://clevertap-prod.com/hello`
> Updated hello request URL

- CHANGELOG.md
- README.md
- docs/Variables.md
- Updated CHANGELOG.md. 
- Added Variables.md
> Prepare v5.0.0

- ObjCStarter/ObjCStarter/CTWebViewVC.m
- ObjCStarter/ObjCStarter/sampleHTMLCode.html
- SPMStarter/SPMStarter/CTWebviewVC.swift
- SPMStarter/SPMStarter/sampleHTMLCode.html
- SwiftStarter/SwiftStarter/CTWebviewVC.swift
- SwiftStarter/SwiftStarter/Supporting Files/sampleHTMLCode.html
- Used unique identifier for script message handler in CleverTapJSInterface
> [SDK-3049] Updated sample apps for web view

- CleverTapSDK.xcodeproj/project.pbxproj
- CleverTapSDK/include/LeanplumCT.h
- CleverTapSDK/ios.modulemap
- CleverTapSDK/tvos.modulemap
Fixed a bug where the LP interface was not working for SPM and manual integrations
> LP interface fix

- CleverTapSDK/Inbox/models/CleverTapInboxMessage.m
- It can be accessed directly using property `customData`.
> [SDK-3166] Added custom key-value in app inbox message

- CleverTapSDK/CleverTap.m
- Added "debug" key in the header of payload for integration debugger implementation
> SDK-3203-IntegrationDebugger

- CleverTapSDK/CTDeviceInfo.h
- CleverTapSDK/CTDeviceInfo.m
- CleverTapSDK/CleverTap.h
- CleverTapSDK/CleverTap.m
- Implemented System Locale class to get Language and Country for LP Parity
> SDK-3221_UseLocaleClassForLanguageNConuntry-LPParity

- CleverTapSDK.xcodeproj/project.pbxproj
- CleverTapSDK/CTAES.m
- CleverTapSDK/CTDispatchQueueManager.h
- CleverTapSDK/CTDispatchQueueManager.m
- CleverTapSDK/CTInAppFCManager.m
- CleverTapSDK/CTPushPrimerManager.h
- CleverTapSDK/CTPushPrimerManager.m
- CleverTapSDK/CleverTap.h
- CleverTapSDK/CleverTap.m
- CleverTapSDK/CleverTapInternal.h
- CleverTapSDK/InApps/CTAlertViewController.m
- CleverTapSDK/InApps/CTImpressionManager.m
- CleverTapSDK/InApps/CTInAppDisplayManager.h
- CleverTapSDK/InApps/CTInAppDisplayManager.m
- CleverTapSDK/InApps/CTInAppEvaluationManager.m
- CleverTapSDK/InApps/Matchers/CTEventAdapter.h
- CleverTapSDK/InApps/Matchers/CTTriggerAdapter.h
- CleverTapSDK/NSDictionary+Extensions.h
- CleverTapSDK/ProductConfig/controllers/CTProductConfigController.m
- CleverTapSDK/ProductExperiences/CTVariables.h
- CleverTapSDK/Swizzling/CTSwizzleManager.h
- CleverTapSDK/Swizzling/CTSwizzleManager.m
- added swizzle and queue managers
- moved private methods to an internal file. 
- added push primer manager.
- fixed xcode analyser warnings
> Modular improvements

- CleverTapSDK/InApps/CustomTemplates/CTAppFunctionBuilder.m
- CleverTapSDK/InApps/CustomTemplates/CTCustomTemplateBuilder-Internal.h
- CleverTapSDK/InApps/CustomTemplates/CTCustomTemplateBuilder.h
- CleverTapSDK/InApps/CustomTemplates/CTCustomTemplateBuilder.m
- CleverTapSDK/InApps/CustomTemplates/CTInAppTemplateBuilder.h
- CleverTapSDK/InApps/CustomTemplates/CTInAppTemplateBuilder.m
- CleverTapSDKTests/InApps/CustomTemplates/CTCustomTemplateBuilderTest.m
- Allow dictionaries in Custom App Functions
- Allow argument names with dots (nesting) in Custom App Functions
> [MC-1649] Custom functions allow dictionaries (Custom Templates Part 6)

- CleverTapSDK.xcodeproj/project.pbxproj
- CleverTapSDK/CTConstants.h
- CleverTapSDK/CTLocalDataStore.h
- CleverTapSDK/CTLocalDataStore.m
- CleverTapSDK/CTProfileBuilder.h
- CleverTapSDK/CTProfileBuilder.m
- CleverTapSDK/CTUserInfoMigrator.h
- CleverTapSDK/CTUserInfoMigrator.m
- CleverTapSDK/CTValidator.m
- CleverTapSDK/CleverTap.m
- CleverTapSDK/InApps/CTInAppEvaluationManager.h
- CleverTapSDK/InApps/CTInAppEvaluationManager.m
- CleverTapSDK/InApps/Matchers/CTEventAdapter.h
- CleverTapSDK/InApps/Matchers/CTEventAdapter.m
- CleverTapSDK/InApps/Matchers/CTTriggerAdapter.h
- CleverTapSDK/InApps/Matchers/CTTriggerAdapter.m
- CleverTapSDK/InApps/Matchers/CTTriggersMatcher.m
- Refactor Event adapter and Trigger Adapter to start using profile attribute names
- Added support for User Attribute triggering for Profile Increment and Profile Decrement API
> SDK-3824 Refactor adapter to start using profile attribute names

- CleverTapSDK.xcodeproj/project.pbxproj
- CleverTapSDK/CTLocalDataStore.m
- CleverTapSDK/CTUserInfoMigrator.h
- CleverTapSDK/CTUserInfoMigrator.m
- CleverTapSDK/CleverTap.m
- Change persistence logic to use accountID and deviceID
- Persistence migration to new UserInfo cache including accountID and deviceID
> Task/sdk 3823/Persistence migration

- CHANGELOG.md
- README.md
- docs/CustomCodeTemplates.md
- docs/Variables.md
Add documentation for Custom Code Templates integration and code examples.
Add emojis to match the document style. Add Custom Code Templates section.
Update Variables doc to include File Type Variables documentation.
Add the log for the changes included.
> Update docs, Changelog and README

- CleverTapSDK/InApps/CTInAppDisplayManager.m
In-app on `AppLaunched` event will not be displayed if the app is backgrounded right after the start. 
If the app is backgrounded right after the start, before the in-app is displayed, the in-app will not be displayed and will block the in-app queue.
The CleverTap instance `isAppForeground` is updated when the `UIApplication` state notifications are posted (`UIApplicationDidBecomeActiveNotification`, `UIApplicationDidEnterBackgroundNotification`). However, those are triggered after the application state has changed. This means that `isAppForeground` will be true but the application state will _no longer be_ `UIApplicationStateActive`.
Check if the `UIApplicationState` is `UIApplicationStateActive`. This requires to be run on the main thread, so the checks has to be moved from the …
> [MC-2054] Check the application state for in-apps

- CleverTapSDK/CTPlistInfo.h
- CleverTapSDK/CTPlistInfo.m
- CleverTapSDK/CleverTap.h
- CleverTapSDK/CleverTap.m
- CleverTapSDK/CleverTapInstanceConfig.m
- CleverTapSDK/CleverTapInstanceConfigPrivate.h
added `setCredentials` method for custom handshake domain
> Added setCredentials method for custom handshake domain

- Package.swift
Updated checksum of Package.swift for v7.2.1
> Updated checksum of Package.swift
